show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/QuantumESPRESSOParser.jl/archive/refs/tags/v0.1.0.zip
  tar_url: https://github.com/MineralsCloud/QuantumESPRESSOParser.jl/archive/refs/tags/v0.1.0.tar.gz
