name = "QuantumESPRESSOParsers"
uuid = "a780ab42-b33a-11e9-16c1-a92d75b2a626"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
